#开发环境配置文件

server:
  port: 80
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
  compression:
    enabled: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  mvc:
    throw-exception-if-no-handler-found: true #没有绑定的url直接抛出错误

  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///blogserver?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: aion
    driverClassName: com.mysql.cj.jdbc.Driver
    # 连接池参数
    druid:
      initial-size: 8
      min-idle: 5
      max-active: 10
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800

  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false

#阿里云OSS密钥和链接参数
oss:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:
  fileHost:
#日志
logging:
  file: logs/htwokey.log
  level:
    root: info
    com.htwokey.blog.mapper: debug
  pattern:
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"

